version: '3'
services:
  pmk-node:
    build: .
    image: centos7-pind
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - type: bind
        source: ./container_images
        target: /container_images
    tmpfs: /run
    privileged: true
    env_file: ./env
    environment:
      container: docker
    deploy:
      resources:
        limits:
          cpus: 2
          memory: "2048M"
